###ACCUEIL
GET http://localhost:5000/

###GET ALL ARTWORKS
GET http://localhost:5000/artwork

### GET ONE CATEGORY
GET http://localhost:5000/artwork/portrait

### GET ONE ARTWORK
GET http://localhost:5000/artwork/portrait/2

### GET ALL NEWS
GET http://localhost:5000/news

### GET INFO ARTIST
GET http://localhost:5000/about

### GET ALL PAINTINGS
GET http://localhost:5000/artwork/paintings

###LOGIN
POST http://localhost:5000/admin
content-type: application/json

{
    "mail": "artiste@gmail.com",
    "password" : "1234"
}

