###ACCUEIL
GET http://localhost:5000/

###GET ALL PAINTINGS
GET http://localhost:5000/artwork/painting

### GET ONE CATEGORY
GET http://localhost:5000/artwork/oil-painting

### GET ONE ARTWORK
GET http://localhost:5000/artwork/mural-painting/10
### GET ALL NEWS
GET http://localhost:5000/news/

### GET INFO ARTIST
GET http://localhost:5000/about

###SEND MESSAGE
POST http://localhost:5000/contact
content-type: application/json

{
    "name": "VIR",
    "firstname" : "Flo",
    "email": "flo.vir@outlook.com",
    "message": "salut!!" 
}

#################ADMIN####################

###LOGIN
POST http://localhost:5000/admin
content-type: application/json

{
    "email": "camillepaul.pro@gmail.com",
    "password" : "1234"
}

### GET ADMIN HOME WITH ALL ARTWORK
GET http://localhost:5000/admin/home
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzAzOTY0NTIsImV4cCI6MTYzMDQwMDA1Mn0.oIdG7WLN_loTTkGs6sSRX1ZcoYLDzEBcnnVPGTteUMw

### ADD PICTURE FOR HOME
POST http://localhost:5000/admin/home
content-type: application/json

{
    "name_picture": "moi dans le désert",
    "image" : "desert.png",
    "description": "j'adore le désert"
}

### DELETE HOME PICTURE
DELETE http://localhost:5000/admin/home/37

### UPDATE HOME PICTURE
PATCH http://localhost:5000/admin/home/1

### GET ALL ARTWORK
GET http://localhost:5000/admin/artwork

### GET ALL ARTWORK OF ONE CATEGORY
GET http://localhost:5000/admin/artwork/portrait

### ADD ARTWORK 
POST http://localhost:5000/admin/artwork
content-type: application/json

{
    "name_artwork": "Portrait test",
    "date" : "2019",
    "place": "Orleans",
    "format": "30 x 30 cm",
    "description": "peinture sur du lin",
    "category_id": 2,
    "artist_id":1,
    "image": "https://firebasestorage.googleapis.com/v0/b/projet-peintre.appspot.com/o/D2.%20Portrait%201.jpg?alt=media&token=5c6e3ad8-8916-4172-b8ab-47eb880c2e35"
}

### DELETE ARTWORK BY CATEGORY
DELETE http://localhost:5000/admin/artwork/14

### UPDATE ARTWORK BY CATEGORY
PATCH http://localhost:5000/admin/artwork/portrait/2
content-type: application/json

{
    "name_artwork": "bateau_update",
    "date" : "2019-05-20",
    "place": "Orleans_update",
    "height": 20,
    "width": 30,
    "support": "papier",
    "category_id": 1,
    "artist_id":1,
    "name_picture": "blé",
    "image": "data/picture/ble.png",
    "description": "un nouveau beau champ de blé"
}

### GET ALL NEWS
GET http://localhost:5000/admin/news

### ADD NEWS
POST http://localhost:5000/admin/news
content-type: application/json

{
    "date": "2017-05-23",
    "place": "Lille",
    "article": "expo à Lille",
    "name_picture": "expo_lille",
    "image": "expo_lille.png",
    "description": "cool Lille"
}

### DELETE NEWS
DELETE http://localhost:5000/admin/news/1

### UPDATE NEWS
PATCH http://localhost:5000/admin/news/2
content-type: application/json

{
    "date": "2017-05-23",
    "place": "Lille",
    "article": "update de expo à Paris",
    "name_picture": "Lille_expo", 
    "image": "Lille_expo.png",
    "description": "expo a Lille cool"
}
