### GET ONE CATEGORY
GET http://localhost:5000/artwork/portrait

### GET ONE ARTWORK
GET http://localhost:5000/artwork/portrait/2

### GET ALL NEWS
GET http://localhost:5000/news

### GET INFO ARTIST
GET http://localhost:5000/about
